"""empty message

Revision ID: 370c395989aa
Revises: d61cad33ff07
Create Date: 2019-12-16 13:43:20.525196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370c395989aa'
down_revision = 'd61cad33ff07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comment_child', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='comment_items_comment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comment_items_pkey')
    )
    # ### end Alembic commands ###
