"""empty message

Revision ID: 5f230ac0859f
Revises: 40637f0c176c
Create Date: 2019-12-12 13:53:48.134169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f230ac0859f'
down_revision = '40637f0c176c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_tours', sa.Column('name_tour', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_tours', 'name_tour')
    # ### end Alembic commands ###
