"""empty message

Revision ID: 83b0827297d4
Revises: ba8d4d418e88
Create Date: 2019-12-11 19:29:56.637095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b0827297d4'
down_revision = 'ba8d4d418e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_tours', sa.Column('book_date', sa.Date(), nullable=True))
    op.add_column('book_tours', sa.Column('languages', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_tours', 'languages')
    op.drop_column('book_tours', 'book_date')
    # ### end Alembic commands ###
