"""empty message

Revision ID: 96230d25f15b
Revises: 83b0827297d4
Create Date: 2019-12-12 10:22:06.401895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96230d25f15b'
down_revision = '83b0827297d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_tour_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_tourItem_id', sa.Integer(), nullable=False),
    sa.Column('payment', sa.Integer(), nullable=False),
    sa.Column('languages', sa.String(length=255), nullable=True),
    sa.Column('book_date', sa.Date(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['book_tourItem_id'], ['book_tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book_tours', sa.Column('dates', sa.Date(), nullable=True))
    op.add_column('book_tours', sa.Column('number_people', sa.Integer(), nullable=True))
    op.drop_column('book_tours', 'country')
    op.drop_column('book_tours', 'last_name')
    op.drop_column('book_tours', 'email')
    op.drop_column('book_tours', 'phone')
    op.drop_column('book_tours', 'payment')
    op.drop_column('book_tours', 'first_name')
    op.drop_column('book_tours', 'book_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_tours', sa.Column('book_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('book_tours', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('book_tours', sa.Column('payment', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('book_tours', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('book_tours', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('book_tours', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('book_tours', sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('book_tours', 'number_people')
    op.drop_column('book_tours', 'dates')
    op.drop_table('book_tour_items')
    # ### end Alembic commands ###
