"""empty message

Revision ID: c16612754296
Revises: 370c395989aa
Create Date: 2019-12-16 14:55:25.531310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16612754296'
down_revision = '370c395989aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_tour_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'tours', ['tour_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_tour_id_fkey', 'comments', 'book_tours', ['tour_id'], ['id'])
    # ### end Alembic commands ###
