"""empty message

Revision ID: de4a5566d0d6
Revises: 5f230ac0859f
Create Date: 2019-12-12 23:13:25.169631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de4a5566d0d6'
down_revision = '5f230ac0859f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_tour_items', sa.Column('tour_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_tour_items', 'tour_name')
    # ### end Alembic commands ###
